name: CI

on:
  push:
    branches: '**'
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
     TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
     TURBO_TEAM: ${{ vars.TURBO_TEAM }}

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install jq
        uses: dcarbone/install-jq-action@v3

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Check
        run: pnpm check

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test
      - name: Capture New Release Version
        run: |
          pnpm changeset status --output=release.json
          echo "NEW_VERSION=$(jq -r '.releases[0].newVersion' release.json); PKG_NAME=$(jq -r '.releases[0].name' release.json)" >> "$GITHUB_ENV"
          rm release.json
      - name: Release
        id: changesets
        uses: changesets/action@v1
        with:
          title: "chore: release ${{ env.PKG_NAME }}@${{ env.NEW_VERSION }}"
          commit: ""
          publish: pnpm publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}