on:
  push:
    branches: '**'
  pull_request:
    types: [opened, synchronize]
  workflow_call:
    inputs:
      run-name:
        required: false
        description: 'Name of the workflow'
        type: string
name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
run-name: ${{inputs.run-name}}

jobs:
  setup:
    name: Setup node, pnpm and install
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2
      
      - name: Setup node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Install
        run: pnpm install --frozen-lockfile
  build:
    name: Build
    runs-on: ubuntu-latest
    needs: [setup]
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      FORCE_COLOR: "1"
    steps:
      - name: Check
        run: pnpm check

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [setup]
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      FORCE_COLOR: "1"
    steps:
      - name: Test with coverage
        run: pnpm test:cov

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
  release:
    name: Test
    runs-on: ubuntu-latest
    needs: [setup, build, test]
    env:
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ vars.TURBO_TEAM }}
      FORCE_COLOR: "1"
    steps:
      - name: Release
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}