name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
run-name: ${{inputs.run-name}}
on:
  push:
    branches: '**'
  pull_request:
    types: [opened, synchronize]
  workflow_call:
    inputs:
      test-matrix-os:
        description: 'Os on which to run the test job, this is a JSON string of string[], will be passed to fromJSON'
        default: '["ubuntu-latest"]'
        type: string
        required: false
      test-matrix-node:
        description: 'Node version on which to run the test job, this is a JSON string of string[], will be passed to fromJSON'
        default: '[20, 22]'
        type: string
        required: false
      run-name:
        required: false
        description: 'Name of the workflow'
        type: string

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  FORCE_COLOR: "1"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Setup
        uses: elcoosp/ghca-node-pnpm@v1.1
      - name: Check
        run: pnpm check
      - name: Build
        run: pnpm build

  test:
    name: Test
    strategy:
      matrix:
        os: ${{ fromJSON(inputs.test-matrix-os) }}
        node: ${{ fromJSON(inputs.test-matrix-node) }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup
        uses: elcoosp/ghca-node-pnpm@v1.1
        with:
          node-version: ${{ matrix.node }}
      - name: Test with coverage
        run: pnpm test:cov
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build, test]
    steps:
      - name: Setup
        uses: elcoosp/ghca-node-pnpm@v1.1
      - name: Release
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}