name: CI
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
run-name: ${{inputs.run-name}}
on:
  push:
    branches: '**'
  pull_request:
    types: [opened, synchronize]
  workflow_call:
    inputs:
      run-name:
        required: false
        description: 'Name of the workflow'
        type: string

env:
  TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
  TURBO_TEAM: ${{ vars.TURBO_TEAM }}
  FORCE_COLOR: "1"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: elcoosp/ghca-node-pnpm@v1.1
      - run: pnpm check
      - run: pnpm build

  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18, 20]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: elcoosp/ghca-node-pnpm@v1.1
        with:
          node-version: ${{ matrix.node }}
      - run: pnpm test

  test-coverage:
    name: Test coverage
    runs-on: ubuntu-latest
    steps:
      - uses: elcoosp/ghca-node-pnpm@v1.1
      - run: pnpm test:cov
      - uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [build, test, test-coverage]
    steps:
      - uses: elcoosp/ghca-node-pnpm@v1.1
      - name: Release
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm publish-packages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}